import mlflow
import mlflow.sklearn

mlflow.set_tracking_uri("sqlite:///mlflow.db")
apiVersion: apps/v1
kind: Deployment
EXPERIMENT_NAME = "Flight Price Prediction - Random Forest"
metadata:
  name: travel-analytics

spec:
  replicas: 1

  selector:
    matchLabels:
      app: travel-analytics

  template:
    metadata:
      labels:
        app: travel-analytics

    spec:
      containers:
        - name: travel-analytics

          image: ghcr.io/ashwimaske13-gif/travel-analytics-mlops:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5